### ISSUE TITLE
The pre-trained mobileNet model

### ISSUE THREAD

**Issue by ElvishElvis** [bogireddytejareddy/retinaface-pytorch#1]
Thank you for your work!
btw, can your training script be used on the training of the mobileNet v1 released in your other repo? And when could you release the latest model?

I am currently working on 68 landmark with small model, please refer to my git for more info thanks

**Comment by bogireddytejareddy** [comment]
You can add mobilenet backbone instead of efficientnet, it shouldn't be hard. I am training my models, might release by end of september

**Comment by ElvishElvis** [comment]
Yes I understand that. 
However, in your other repo, you do convert a model from MXNET to pytorch, and that model is very very well on testing. I am asking if your code can keep training that model that came from MXNET?

**Comment by ElvishElvis** [comment]
When I trained mobileNet from scratch, it is not as good as the MXNET one.

**Comment by bogireddytejareddy** [comment]
No, my code can't train that model. I reverse engineered mxnet model to create pytorch model, I don't have training code for that model.
